# Archivo de secretos para desarrollo local
# Puedes dejar las comillas vac√≠as "" para probar

BINANCE_API_KEY = ""
BINANCE_SECRET = ""
TELEGRAM_TOKEN = ""
TELEGRAM_CHAT_ID = ""
COINGLASS_API_KEY = ""

[CRYPTOPANIC]
API_KEY = ""